### ISSUE TITLE
TypeError: cannot assign 'list' object to buffer 'CatBN_output_buffer' (torch Tensor or None required)

### ISSUE THREAD

**Issue by chennupati** [gpleiss/temperature_scaling#5]
Hi There, I am trying to run your code, and I got the following error. Can you help me fix this asap.

Files already downloaded and verified
<type 'list'>
Traceback (most recent call last):
  File "train.py", line 262, in <module>
    fire.Fire(train)
  File "/home/gchennupati/.local/lib/python2.7/site-packages/fire/core.py", line 127, in Fire
    component_trace = _Fire(component, args, context, name)
  File "/home/gchennupati/.local/lib/python2.7/site-packages/fire/core.py", line 366, in _Fire
    component, remaining_args)
  File "/home/gchennupati/.local/lib/python2.7/site-packages/fire/core.py", line 542, in _CallCallable
    result = fn(*varargs, **kwargs)
  File "train.py", line 200, in train
    num_classes=100
  File "/home/gchennupati/Work/Cancer/temperature_scaling/models/densenet_efficient_multi_gpu.py", line 215, in __init__
    drop_rate=drop_rate, storage=storage)
  File "/home/gchennupati/Work/Cancer/temperature_scaling/models/densenet_efficient_multi_gpu.py", line 136, in __init__
    self.register_buffer('CatBN_output_buffer', self.storage)
  File "/home/gchennupati/.local/lib/python2.7/site-packages/torch/nn/modules/module.py", line 113, in register_buffer
    .format(torch.typename(tensor), name))
TypeError: cannot assign 'list' object to buffer 'CatBN_output_buffer' (torch Tensor or None required)

**Comment by gpleiss** [comment]
I think it's an issue with the densenet model. Try running it with a different model.

**Comment by gpleiss** [comment]
See #7
